name: Caching with Tuist Dependencies

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  CACHED_DEPENDENCY_PATHS: ${{ github.workspace }}/Tuist/Dependencies

jobs:
  caching-dependencies:
    name: 🧩 Caching Dependencies
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - uses: jdx/mise-action@v2
         with:
           xcode-version: 15.2

      - name: Compute dependency cache key
        id: compute_hash
        run: echo "hash=${{ hashFiles('Tuist/Dependencies.swift') }}" >> $GITHUB_OUTPUT

      - name: Check dependency key
        uses: actions/cache@v3
        id: cache_dependencies
        with:
          path: ${{ env.CACHED_DEPENDENCY_PATHS }}
          key: ${{ steps.compute_hash.outputs.hash }}

      - name: Install tuist
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: mise install tuist

      - name: Install dependencies
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: tuist install

    outputs:
      dependency_cache_key: ${{ steps.compute_hash.outputs.hash }}
          

