name: pr

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
      with:
        swift-version: "5.5.2"
        xcode-version: latest
    - name: install tuist
      run: curl -Ls https://install.tuist.io | bash
    - name: project Generate
      run: |
        tuist generate
    - name: Tests
      run: |
        xcodebuild clean test -workspace GCMS.xcworkspace -scheme 'GCMSTest' -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'
